### ISSUE TITLE
dqlite stacktrace while running lxd CI tests

### ISSUE THREAD

**Issue by MathieuBordere** [canonical/dqlite#301]
see https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/3473/arch=arm64,backend=dir,compiler=golang-1.15/console#console-section-3

```
double free or corruption (top)
SIGABRT: abort
PC=0xffffa607a138 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0xffffa607a138
stack: frame={sp:0xffffd0eb3ce0, fp:0x0} stack=[0xffffd06b5968,0xffffd0eb4990)
0000ffffd0eb3be0:  0000ffffd0eb4120  0000ffffa5eaa3e8 
0000ffffd0eb3bf0:  0000000023714ae0  0000000000000005 
0000ffffd0eb3c00:  0000000000000041  0000000000000017 
0000ffffd0eb3c10:  0000000000000000  00006b6e696c6e75 
0000ffffd0eb3c20:  0000ffffa5eca000  0000000000000028 
0000ffffd0eb3c30:  0000000023710310  0000000000000028 
0000ffffd0eb3c40:  0000ffffd0eb4208  0000000023710318 
0000ffffd0eb3c50:  0000000023710320  0000ffffa5dfef10 
0000ffffd0eb3c60:  0000ffffa5dff710  0000ffffd0eb4200 
0000ffffd0eb3c70:  0000ffffd0eb4208  0000ffffd0eb3f08 
0000ffffd0eb3c80:  0000000000000001  0000000000000001 
0000ffffd0eb3c90:  0000000000000000  0000ffffd0eb3eeb 
0000ffffd0eb3ca0:  0000000000000001  0000000000000000 
0000ffffd0eb3cb0:  0000ffffa651d618  0000ffff0000000d 
0000ffffd0eb3cc0:  0000ffffd0eb3da4  0000000000000000 
0000ffffd0eb3cd0:  0000ffffd0eb3d90  0000ffffa60bf194 
0000ffffd0eb3ce0: <0000ffffd0eb3e10  0000ffffa6066d68 
0000ffffd0eb3cf0:  0000ffffa61b2000  523251626c542e70 
0000ffffd0eb3d00:  2f6f672f57423339  0000000000000000 
0000ffffd0eb3d10:  6c2f6d6f632e6275  2f69632d63786c2f 
0000ffffd0eb3d20:  6d742f646c697562  523251626c542e70 
0000ffffd0eb3d30:  2f6f672f57423339  687469672f637273 
0000ffffd0eb3d40:  6c2f6d6f632e6275  742f64786c2f6378 
0000ffffd0eb3d50:  2e706d742f747365  2f4a4e782f6f4f49 
0000ffffd0eb3d60:  6573616261746164  2f6c61626f6c672f 
0000ffffd0eb3d70:  0000ffffd0eb3e10  0000ffffa6066d10 
0000ffffd0eb3d80:  303030303030302d  fffffffe7fffffff 
0000ffffd0eb3d90:  ffffffffffffffff  ffffffffffffffff 
0000ffffd0eb3da0:  ffffffffffffffff  ffffffffffffffff 
0000ffffd0eb3db0:  ffffffffffffffff  ffffffffffffffff 
0000ffffd0eb3dc0:  ffffffffffffffff  ffffffffffffffff 
0000ffffd0eb3dd0:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0xffffa607a138
stack: frame={sp:0xffffd0eb3ce0, fp:0x0} stack=[0xffffd06b5968,0xffffd0eb4990)
0000ffffd0eb3be0:  0000ffffd0eb4120  0000ffffa5eaa3e8 
0000ffffd0eb3bf0:  0000000023714ae0  0000000000000005 
0000ffffd0eb3c00:  0000000000000041  0000000000000017 
0000ffffd0eb3c10:  0000000000000000  00006b6e696c6e75 
0000ffffd0eb3c20:  0000ffffa5eca000  0000000000000028 
0000ffffd0eb3c30:  0000000023710310  0000000000000028 
0000ffffd0eb3c40:  0000ffffd0eb4208  0000000023710318 
0000ffffd0eb3c50:  0000000023710320  0000ffffa5dfef10 
0000ffffd0eb3c60:  0000ffffa5dff710  0000ffffd0eb4200 
0000ffffd0eb3c70:  0000ffffd0eb4208  0000ffffd0eb3f08 
0000ffffd0eb3c80:  0000000000000001  0000000000000001 
0000ffffd0eb3c90:  0000000000000000  0000ffffd0eb3eeb 
0000ffffd0eb3ca0:  0000000000000001  0000000000000000 
0000ffffd0eb3cb0:  0000ffffa651d618  0000ffff0000000d 
0000ffffd0eb3cc0:  0000ffffd0eb3da4  0000000000000000 
0000ffffd0eb3cd0:  0000ffffd0eb3d90  0000ffffa60bf194 
0000ffffd0eb3ce0: <0000ffffd0eb3e10  0000ffffa6066d68 
0000ffffd0eb3cf0:  0000ffffa61b2000  523251626c542e70 
0000ffffd0eb3d00:  2f6f672f57423339  0000000000000000 
0000ffffd0eb3d10:  6c2f6d6f632e6275  2f69632d63786c2f 
0000ffffd0eb3d20:  6d742f646c697562  523251626c542e70 
0000ffffd0eb3d30:  2f6f672f57423339  687469672f637273 
0000ffffd0eb3d40:  6c2f6d6f632e6275  742f64786c2f6378 
0000ffffd0eb3d50:  2e706d742f747365  2f4a4e782f6f4f49 
0000ffffd0eb3d60:  6573616261746164  2f6c61626f6c672f 
0000ffffd0eb3d70:  0000ffffd0eb3e10  0000ffffa6066d10 
0000ffffd0eb3d80:  303030303030302d  fffffffe7fffffff 
0000ffffd0eb3d90:  ffffffffffffffff  ffffffffffffffff 
0000ffffd0eb3da0:  ffffffffffffffff  ffffffffffffffff 
0000ffffd0eb3db0:  ffffffffffffffff  ffffffffffffffff 
0000ffffd0eb3dc0:  ffffffffffffffff  ffffffffffffffff 
0000ffffd0eb3dd0:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [syscall]:
runtime.cgocall(0x10e6724, 0x4000491a88, 0x4000491a00)
	/snap/go_115/7216/src/runtime/cgocall.go:133 +0x50 fp=0x4000491a50 sp=0x4000491a10 pc=0x40e5a0
github.com/canonical/go-dqlite/internal/bindings._Cfunc_dqlite_node_recover(0x23713498, 0x237104b0, 0x1, 0x0)
	_cgo_gotypes.go:201 +0x44 fp=0x4000491a80 sp=0x4000491a50 pc=0x85f314
github.com/canonical/go-dqlite/internal/bindings.(*Node).Recover.func4(0x23713498, 0x237104b0, 0x1, 0x23711260)
	/lxc-ci/build/tmp.TlbQ2R93BW/go/src/github.com/canonical/go-dqlite/internal/bindings/server.go:205 +0x74 fp=0x4000491ab0 sp=0x4000491a80 pc=0x861624
github.com/canonical/go-dqlite/internal/bindings.(*Node).Recover(0x23713498, 0x4000491c08, 0x1, 0x1, 0x0, 0x0)
	/lxc-ci/build/tmp.TlbQ2R93BW/go/src/github.com/canonical/go-dqlite/internal/bindings/server.go:205 +0x11c fp=0x4000491b90 sp=0x4000491ab0 pc=0x86077c
github.com/canonical/go-dqlite.(*Node).Recover(...)
	/lxc-ci/build/tmp.TlbQ2R93BW/go/src/github.com/canonical/go-dqlite/node.go:113
github.com/lxc/lxd/lxd/cluster.Recover(0x40004c2b00, 0x50, 0x0)
	/lxc-ci/build/tmp.TlbQ2R93BW/go/src/github.com/lxc/lxd/lxd/cluster/recover.go:75 +0x134 fp=0x4000491c50 sp=0x4000491b90 pc=0xcb6514
main.(*cmdClusterRecoverFromQuorumLoss).Run(0x40000f3100, 0x40004ca780, 0x40000f3290, 0x0, 0x1, 0x4000491cd8, 0x0)
	/lxc-ci/build/tmp.TlbQ2R93BW/go/src/github.com/lxc/lxd/lxd/main_cluster.go:124 +0xfc fp=0x4000491cd0 sp=0x4000491c50 pc=0x1018cfc
main.(*cmdClusterRecoverFromQuorumLoss).Run-fm(0x40004ca780, 0x40000f3290, 0x0, 0x1, 0x0, 0x0)
	/lxc-ci/build/tmp.TlbQ2R93BW/go/src/github.com/lxc/lxd/lxd/main_cluster.go:102 +0x48 fp=0x4000491d20 sp=0x4000491cd0 pc=0x10c71d8
github.com/spf13/cobra.(*Command).execute(0x40004ca780, 0x40000f3280, 0x1, 0x1, 0x40004ca780, 0x40000f3280)
	/lxc-ci/build/tmp.TlbQ2R93BW/go/src/github.com/spf13/cobra/command.go:855 +0x30c fp=0x4000491e00 sp=0x4000491d20 pc=0xeea68c
github.com/spf13/cobra.(*Command).ExecuteC(0x40004be280, 0x4000491f48, 0x1, 0x1)
	/lxc-ci/build/tmp.TlbQ2R93BW/go/src/github.com/spf13/cobra/command.go:973 +0x274 fp=0x4000491ee0 sp=0x4000491e00 pc=0xeeafa4
github.com/spf13/cobra.(*Command).Execute(...)
	/lxc-ci/build/tmp.TlbQ2R93BW/go/src/github.com/spf13/cobra/command.go:901
main.main()
	/lxc-ci/build/tmp.TlbQ2R93BW/go/src/github.com/lxc/lxd/lxd/main.go:213 +0xd40 fp=0x4000491f70 sp=0x4000491ee0 pc=0x1016c50
runtime.main()
	/snap/go_115/7216/src/runtime/proc.go:204 +0x20c fp=0x4000491fd0 sp=0x4000491f70 pc=0x43ff7c
runtime.goexit()
	/snap/go_115/7216/src/runtime/asm_arm64.s:1136 +0x4 fp=0x4000491fd0 sp=0x4000491fd0 pc=0x472c54

goroutine 67 [select]:
database/sql.(*DB).connectionOpener(0x40004ccd00, 0x1614960, 0x40000ef1c0)
	/snap/go_115/7216/src/database/sql/sql.go:1126 +0xa8
created by database/sql.OpenDB
	/snap/go_115/7216/src/database/sql/sql.go:740 +0x118

r0      0x0
r1      0xffffd0eb3d08
r2      0x0
r3      0x8
r4      0x0
r5      0xffffa61af000
r6      0xffffffffffffffff
r7      0xffffffffffffffff
r8      0x87
r9      0xffffd0eb3ee0
r10     0xffffffffffffffff
r11     0xffffffffffffffff
r12     0xffffffffffffffff
r13     0xffffffffffffffff
r14     0xffffffffffffffff
r15     0xffffffffffffffff
r16     0xffffffffffffffff
r17     0xffffffffffffffff
r18     0xffffffffffffffff
r19     0xffffffffffffffff
r20     0xffffa5dff010
r21     0xffffa6529000
r22     0xffffd0eb3f80
r23     0xffffa61af000
r24     0x1
r25     0xffffa6171018
r26     0x10
r27     0x12
r28     0xffffa61b0a60
r29     0xffffd0eb3ce0
lr      0xffffd0eb3d08
sp      0xffffd0eb3ce0
pc      0xffffa607a138
fault   0xffff8a82a008
```

**Comment by MathieuBordere** [comment]
Happened again in https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/3660/arch=amd64,backend=random,compiler=golang-1.15/console#console-section-4

**Comment by MathieuBordere** [comment]
and here https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/3666/arch=amd64,backend=random,compiler=golang-1.15/console
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fe9bd7fb008 pc=0x7fe9f566b870]

runtime stack:
runtime.throw(0x16e4700, 0x2a)
	/snap/go_115/7215/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/snap/go_115/7215/src/runtime/signal_unix.go:726 +0x4ac

goroutine 1 [syscall]:
runtime.cgocall(0x13ad4ba, 0xc000259ac8, 0xc000259a00)
	/snap/go_115/7215/src/runtime/cgocall.go:133 +0x5b fp=0xc000259a98 sp=0xc000259a60 pc=0x40f09b
github.com/canonical/go-dqlite/internal/bindings._Cfunc_dqlite_node_recover(0x44db4a8, 0x44d84c0, 0x1, 0x0)
	_cgo_gotypes.go:201 +0x4d fp=0xc000259ac8 sp=0xc000259a98 pc=0x92b5ad
github.com/canonical/go-dqlite/internal/bindings.(*Node).Recover.func4(0x44db4a8, 0x44d84c0, 0x1, 0x44d9270)
	/lxc-ci/build/tmp.b3jZ4b3QHf/go/src/github.com/canonical/go-dqlite/internal/bindings/server.go:205 +0x89 fp=0xc000259af8 sp=0xc000259ac8 pc=0x92dde9
github.com/canonical/go-dqlite/internal/bindings.(*Node).Recover(0x44db4a8, 0xc000259c40, 0x1, 0x1, 0x0, 0x0)
	/lxc-ci/build/tmp.b3jZ4b3QHf/go/src/github.com/canonical/go-dqlite/internal/bindings/server.go:205 +0x18b fp=0xc000259bd0 sp=0xc000259af8 pc=0x92cd0b
github.com/canonical/go-dqlite.(*Node).Recover(...)
	/lxc-ci/build/tmp.b3jZ4b3QHf/go/src/github.com/canonical/go-dqlite/node.go:113
github.com/lxc/lxd/lxd/cluster.Recover(0xc0001171c0, 0x50, 0x0)
	/lxc-ci/build/tmp.b3jZ4b3QHf/go/src/github.com/lxc/lxd/lxd/cluster/recover.go:75 +0x1ca fp=0xc000259c90 sp=0xc000259bd0 pc=0xe8964a
main.(*cmdClusterRecoverFromQuorumLoss).Run(0xc000226e20, 0xc000249680, 0xc000226fb0, 0x0, 0x1, 0x0, 0x0)
	/lxc-ci/build/tmp.b3jZ4b3QHf/go/src/github.com/lxc/lxd/lxd/main_cluster.go:124 +0x147 fp=0xc000259d08 sp=0xc000259c90 pc=0x12b3f47
main.(*cmdClusterRecoverFromQuorumLoss).Run-fm(0xc000249680, 0xc000226fb0, 0x0, 0x1, 0x0, 0x0)
	/lxc-ci/build/tmp.b3jZ4b3QHf/go/src/github.com/lxc/lxd/lxd/main_cluster.go:102 +0x52 fp=0xc000259d50 sp=0xc000259d08 pc=0x1391972
github.com/spf13/cobra.(*Command).execute(0xc000249680, 0xc000226fa0, 0x1, 0x1, 0xc000249680, 0xc000226fa0)
	/lxc-ci/build/tmp.b3jZ4b3QHf/go/src/github.com/spf13/cobra/command.go:855 +0x47c fp=0xc000259e28 sp=0xc000259d50 pc=0x1143a5c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000233180, 0xc000259f58, 0x1, 0x1)
	/lxc-ci/build/tmp.b3jZ4b3QHf/go/src/github.com/spf13/cobra/command.go:973 +0x375 fp=0xc000259f00 sp=0xc000259e28 pc=0x1144675
github.com/spf13/cobra.(*Command).Execute(...)
	/lxc-ci/build/tmp.b3jZ4b3QHf/go/src/github.com/spf13/cobra/command.go:901
main.main()
	/lxc-ci/build/tmp.b3jZ4b3QHf/go/src/github.com/lxc/lxd/lxd/main.go:213 +0xf65 fp=0xc000259f88 sp=0xc000259f00 pc=0x12b1725
runtime.main()
	/snap/go_115/7215/src/runtime/proc.go:204 +0x209 fp=0xc000259fe0 sp=0xc000259f88 pc=0x445669
runtime.goexit()
	/snap/go_115/7215/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000259fe8 sp=0xc000259fe0 pc=0x47bca1

goroutine 36 [select]:
database/sql.(*DB).connectionOpener(0xc00012fee0, 0x18e0e00, 0xc00011b700)
	/snap/go_115/7215/src/database/sql/sql.go:1126 +0xf5
created by database/sql.OpenDB
	/snap/go_115/7215/src/database/sql/sql.go:740 +0x12a
```

**Comment by MathieuBordere** [comment]
new occurence https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/3807/arch=amd64,backend=zfs,compiler=golang-1.15/console#console-section-3

```
double free or corruption (out)
SIGABRT: abort
PC=0x7f45999c918b m=10 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f45999c918b
stack: frame={sp:0x7f45698110f0, fp:0x0} stack=[0x7f4569012128,0x7f4569811d28)
00007f4569810ff0:  0000000000000001  00007f4599930600 
00007f4569811000:  0000000001766368  00007f45994be760 
00007f4569811010:  00007f4599930600  00007f4599930968 
00007f4569811020:  0000000000000000  0000000001766390 
00007f4569811030:  0000000001766398  0000000000000001 
00007f4569811040:  00000000ffffffff  00000000017663b0 
00007f4569811050:  00007f4599992e28  00007f4599db7a10 
00007f4569811060:  00007f4599930968  0000000000000000 
00007f4569811070:  00007f45995749ec  00007f4569811100 
00007f4569811080:  00007f4569811110  00007f459a0511e9 
00007f4569811090:  2f69632d63786c2f  6d742f646c697562 
00007f45698110a0:  6568445a58502e70  2f6f672f65554e4f 
00007f45698110b0:  2f69632d63786c2f  6d742f646c697562 
00007f45698110c0:  6568445a58502e70  2f6f672f65554e4f 
00007f45698110d0:  687469672f637273  6c2f6d6f632e6275 
00007f45698110e0:  742f64786c2f6378  2e706d742f747365 
00007f45698110f0: <0000000000000000  6573616261746164 
00007f4569811100:  2f6c61626f6c672f  0000332d6e65706f 
00007f4569811110:  0000000000000001  0000000000000400 
00007f4569811120:  00007f45698116a0  00007f4599595918 
00007f4569811130:  00007f4544020888  0000000000000080 
00007f4569811140:  00007f4544000020  00007f454401cb60 
00007f4569811150:  0000000000000000  0002ffff00001fa0 
00007f4569811160:  00007f459992fbe0  00007f4544020940 
00007f4569811170:  fffffffe7fffffff  ffffffffffffffff 
00007f4569811180:  ffffffffffffffff  ffffffffffffffff 
00007f4569811190:  ffffffffffffffff  ffffffffffffffff 
00007f45698111a0:  ffffffffffffffff  ffffffffffffffff 
00007f45698111b0:  ffffffffffffffff  ffffffffffffffff 
00007f45698111c0:  ffffffffffffffff  ffffffffffffffff 
00007f45698111d0:  ffffffffffffffff  ffffffffffffffff 
00007f45698111e0:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7f45999c918b
stack: frame={sp:0x7f45698110f0, fp:0x0} stack=[0x7f4569012128,0x7f4569811d28)
00007f4569810ff0:  0000000000000001  00007f4599930600 
00007f4569811000:  0000000001766368  00007f45994be760 
00007f4569811010:  00007f4599930600  00007f4599930968 
00007f4569811020:  0000000000000000  0000000001766390 
00007f4569811030:  0000000001766398  0000000000000001 
00007f4569811040:  00000000ffffffff  00000000017663b0 
00007f4569811050:  00007f4599992e28  00007f4599db7a10 
00007f4569811060:  00007f4599930968  0000000000000000 
00007f4569811070:  00007f45995749ec  00007f4569811100 
00007f4569811080:  00007f4569811110  00007f459a0511e9 
00007f4569811090:  2f69632d63786c2f  6d742f646c697562 
00007f45698110a0:  6568445a58502e70  2f6f672f65554e4f 
00007f45698110b0:  2f69632d63786c2f  6d742f646c697562 
00007f45698110c0:  6568445a58502e70  2f6f672f65554e4f 
00007f45698110d0:  687469672f637273  6c2f6d6f632e6275 
00007f45698110e0:  742f64786c2f6378  2e706d742f747365 
00007f45698110f0: <0000000000000000  6573616261746164 
00007f4569811100:  2f6c61626f6c672f  0000332d6e65706f 
00007f4569811110:  0000000000000001  0000000000000400 
00007f4569811120:  00007f45698116a0  00007f4599595918 
00007f4569811130:  00007f4544020888  0000000000000080 
00007f4569811140:  00007f4544000020  00007f454401cb60 
00007f4569811150:  0000000000000000  0002ffff00001fa0 
00007f4569811160:  00007f459992fbe0  00007f4544020940 
00007f4569811170:  fffffffe7fffffff  ffffffffffffffff 
00007f4569811180:  ffffffffffffffff  ffffffffffffffff 
00007f4569811190:  ffffffffffffffff  ffffffffffffffff 
00007f45698111a0:  ffffffffffffffff  ffffffffffffffff 
00007f45698111b0:  ffffffffffffffff  ffffffffffffffff 
00007f45698111c0:  ffffffffffffffff  ffffffffffffffff 
00007f45698111d0:  ffffffffffffffff  ffffffffffffffff 
00007f45698111e0:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [syscall]:
runtime.cgocall(0x13b55ef, 0xc0003dbac8, 0xc0003dba00)
	/snap/go_115/7710/src/runtime/cgocall.go:133 +0x5b fp=0xc0003dba98 sp=0xc0003dba60 pc=0x40f0bb
github.com/canonical/go-dqlite/internal/bindings._Cfunc_dqlite_node_recover(0x7f454401f2b8, 0x7f454401c0f0, 0x1, 0x0)
	_cgo_gotypes.go:201 +0x4d fp=0xc0003dbac8 sp=0xc0003dba98 pc=0x92c9ad
github.com/canonical/go-dqlite/internal/bindings.(*Node).Recover.func4(0x7f454401f2b8, 0x7f454401c0f0, 0x1, 0x7f454401cea0)
	/lxc-ci/build/tmp.PXZDheONUe/go/src/github.com/canonical/go-dqlite/internal/bindings/server.go:205 +0x89 fp=0xc0003dbaf8 sp=0xc0003dbac8 pc=0x92f1e9
github.com/canonical/go-dqlite/internal/bindings.(*Node).Recover(0x7f454401f2b8, 0xc0003dbc40, 0x1, 0x1, 0x0, 0x0)
	/lxc-ci/build/tmp.PXZDheONUe/go/src/github.com/canonical/go-dqlite/internal/bindings/server.go:205 +0x18b fp=0xc0003dbbd0 sp=0xc0003dbaf8 pc=0x92e10b
github.com/canonical/go-dqlite.(*Node).Recover(...)
	/lxc-ci/build/tmp.PXZDheONUe/go/src/github.com/canonical/go-dqlite/node.go:113
github.com/lxc/lxd/lxd/cluster.Recover(0xc0000b4980, 0x50, 0x0)
	/lxc-ci/build/tmp.PXZDheONUe/go/src/github.com/lxc/lxd/lxd/cluster/recover.go:75 +0x1ca fp=0xc0003dbc90 sp=0xc0003dbbd0 pc=0xe8876a
main.(*cmdClusterRecoverFromQuorumLoss).Run(0xc0003ca210, 0xc00045ac80, 0xc0003ca3a0, 0x0, 0x1, 0x0, 0x0)
	/lxc-ci/build/tmp.PXZDheONUe/go/src/github.com/lxc/lxd/lxd/main_cluster.go:124 +0x147 fp=0xc0003dbd08 sp=0xc0003dbc90 pc=0x12ba4c7
main.(*cmdClusterRecoverFromQuorumLoss).Run-fm(0xc00045ac80, 0xc0003ca3a0, 0x0, 0x1, 0x0, 0x0)
	/lxc-ci/build/tmp.PXZDheONUe/go/src/github.com/lxc/lxd/lxd/main_cluster.go:102 +0x52 fp=0xc0003dbd50 sp=0xc0003dbd08 pc=0x1398d32
github.com/spf13/cobra.(*Command).execute(0xc00045ac80, 0xc0003ca390, 0x1, 0x1, 0xc00045ac80, 0xc0003ca390)
	/lxc-ci/build/tmp.PXZDheONUe/go/src/github.com/spf13/cobra/command.go:855 +0x47c fp=0xc0003dbe28 sp=0xc0003dbd50 pc=0x1148f7c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003f8780, 0xc0003dbf58, 0x1, 0x1)
	/lxc-ci/build/tmp.PXZDheONUe/go/src/github.com/spf13/cobra/command.go:973 +0x375 fp=0xc0003dbf00 sp=0xc0003dbe28 pc=0x1149b95
github.com/spf13/cobra.(*Command).Execute(...)
	/lxc-ci/build/tmp.PXZDheONUe/go/src/github.com/spf13/cobra/command.go:901
main.main()
	/lxc-ci/build/tmp.PXZDheONUe/go/src/github.com/lxc/lxd/lxd/main.go:213 +0xf65 fp=0xc0003dbf88 sp=0xc0003dbf00 pc=0x12b7ca5
runtime.main()
	/snap/go_115/7710/src/runtime/proc.go:204 +0x209 fp=0xc0003dbfe0 sp=0xc0003dbf88 pc=0x445689
runtime.goexit()
	/snap/go_115/7710/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0003dbfe8 sp=0xc0003dbfe0 pc=0x47bd41

goroutine 41 [select]:
database/sql.(*DB).connectionOpener(0xc0000bb040, 0x18ed380, 0xc0000b6f40)
	/snap/go_115/7710/src/database/sql/sql.go:1126 +0xf5
created by database/sql.OpenDB
	/snap/go_115/7710/src/database/sql/sql.go:740 +0x12a

rax    0x0
rbx    0x7f4569812700
rcx    0x7f45999c918b
rdx    0x0
rdi    0x2
rsi    0x7f45698110f0
rbp    0x7f4569811440
rsp    0x7f45698110f0
r8     0x0
r9     0x7f45698110f0
r10    0x8
r11    0x246
r12    0x7f4569811360
r13    0x10
r14    0x7f459a071000
r15    0x1
rip    0x7f45999c918b
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```
