### ISSUE TITLE
Assertion failure in transport__write

### ISSUE THREAD

**Issue by cole-miller** [canonical/dqlite#427]
This is from Jepsen again, see the [CI run](https://github.com/canonical/jepsen.dqlite/actions/runs/3382125371/jobs/5616724176). It's this assertion:

https://github.com/canonical/dqlite/blob/4fde1a89b4e230a1546c067c681eb67aff6bf846/src/lib/transport.c#L178

**Comment by MathieuBordere** [comment]
Still being hit in https://github.com/canonical/jepsen.dqlite/actions/runs/3384785679/jobs/5622162507, requires more careful investigation. Unless Github is caching the dqlite repo checkout somehow, but I don't think so.

**Comment by MathieuBordere** [comment]
```
(gdb) bt
#0  runtime.raise () at /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/sys_linux_amd64.s:165
#1  0x000000000044e9ed in runtime.raisebadsignal (sig=6, c=0x7fb755db3ee8) at /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/signal_unix.go:833
#2  0x000000000044eda5 in runtime.badsignal (sig=6, c=0x7fb755db3ee8) at /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/signal_unix.go:952
#3  0x000000000044d7cb in runtime.sigtrampgo (sig=6, info=0x7fb755db40b0, ctx=0x7fb755db3f80) at /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/signal_unix.go:442
#4  0x000000000046b88e in runtime.sigtrampgo (sig=6, info=0x7fb755db40b0, ctx=0x7fb755db3f80) at <autogenerated>:1
#5  0x000000000046adbd in runtime.sigtramp () at /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/sys_linux_amd64.s:343
#6  <signal handler called>
#7  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#8  0x00007fb780cd7859 in __GI_abort () at abort.c:79
#9  0x00007fb780cd7729 in __assert_fail_base (fmt=0x7fb780e6d588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7fb780ecf0af "t->write_cb == NULL", 
    file=0x7fb780ecf020 "src/lib/transport.c", line=178, function=<optimized out>) at assert.c:92
#10 0x00007fb780ce8fd6 in __GI___assert_fail (assertion=assertion@entry=0x7fb780ecf0af "t->write_cb == NULL", file=file@entry=0x7fb780ecf020 "src/lib/transport.c", 
    line=line@entry=178, function=function@entry=0x7fb780ecf0e0 <__PRETTY_FUNCTION__.9778> "transport__write") at assert.c:101
#11 0x00007fb780ec2824 in transport__write (t=<optimized out>, buf=<optimized out>, cb=<optimized out>) at src/lib/transport.c:178
#12 0x00007fb780eb6f8e in gateway_handle_cb (req=<optimized out>, status=<optimized out>, type=0) at src/conn.c:86
#13 0x00007fb780eb9fc4 in failure (req=0x7fb744003008, code=<optimized out>, message=<optimized out>) at src/gateway.c:182
#14 0x00007fb780ebbd2b in handle_exec_sql_next (req=0x7fb744003008, done=done@entry=false) at src/gateway.c:662
#15 0x00007fb780ebbf6a in execSqlBarrierCb (barrier=0x7fb744002f70, status=0) at src/gateway.c:704
#16 0x00007fb780ec096f in raftBarrierCb (req=0x7fb744002f80, status=<optimized out>) at src/leader.c:430
#17 0x00007fb780ad681d in applyBarrier (index=388, r=0xcc8960) at src/replication.c:1368
#18 replicationApply (r=r@entry=0xcc8960) at src/replication.c:1605
#19 0x00007fb780ad8057 in replicationUpdate (r=r@entry=0xcc8960, server=0x7fb74404b380, result=result@entry=0x7fb744037b18) at src/replication.c:756
#20 0x00007fb780ad3852 in recvAppendEntriesResult (r=r@entry=0xcc8960, id=1430860652164524365, address=<optimized out>, result=0x7fb744037b18)
    at src/recv_append_entries_result.c:64
#21 0x00007fb780ad2acb in recvMessage (message=0x7fb744037b00, r=0xcc8960) at src/recv.c:45
#22 recvCb (io=<optimized out>, message=0x7fb744037b00) at src/recv.c:108
#23 0x00007fb780ae434c in uvFireRecvCb (s=s@entry=0x7fb744037aa0) at src/uv_recv.c:190
#24 0x00007fb780ae4868 in uvServerReadCb (stream=<optimized out>, nread=<optimized out>, buf=<optimized out>) at src/uv_recv.c:294
#25 0x00007fb780b47ba1 in ?? () from /lib/x86_64-linux-gnu/libuv.so.1
#26 0x00007fb780b486d8 in ?? () from /lib/x86_64-linux-gnu/libuv.so.1
#27 0x00007fb780b4db80 in uv.io_poll () from /lib/x86_64-linux-gnu/libuv.so.1
#28 0x00007fb780b3d84c in uv_run () from /lib/x86_64-linux-gnu/libuv.so.1
#29 0x00007fb780ec48e0 in taskRun (d=0xcc8098) at src/server.c:597
#30 taskStart (arg=0xcc8098) at src/server.c:623
#31 0x00007fb781054609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#32 0x00007fb780dd4133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
